Tarantool compatibility
tarantool/stat pull request #21
Opened 2019-03-12 15:46 UTC by Satbek

2019-03-12 15:56 UTC, Totktonada requested changes
Please, fix comments below and squash commits.

2019-03-12 15:56 UTC, Totktonada commented on stat/init.lua
> +            if type(v) == "table" then
Nit: single quotes is used around, so it would be looks better if you'll use single quotes here too.

2019-03-12 15:56 UTC, Totktonada commented on stat/init.lua
> +       	end
Broken indent.

2019-03-12 15:56 UTC, Totktonada commented on stat/init.lua
> +	        stats['stat.net.' .. k:lower() .. '.total'] = v.total
Broken indent.

2019-03-12 15:59 UTC, Totktonada commented
It would be good to provide more specific title for the PR, like 'Fix box.stat.net() traversal for recent tarantools' or kinda.

2019-03-12 16:18 UTC, rosik commented
I think it would be better to explicitly traverse keys `SENT` and `RECEIVED` instead of using `pairs`.
It would be easier to understand the code.

2019-03-13 09:36 UTC, Totktonada commented
@rosik Good idea.

2019-03-13 16:39 UTC, Totktonada commented on stat/init.lua
> +        for k, v in pairs({SENT = i.SENT, RECEIVED = i.RECEIVED}) do
Tricky way :) As far as I understand Yaroslav proposed to do it in the most obvious way:

```lua
local box_stat_net = box.stat.net()
stats['stat.net.SENT.total'] = box_stat_net.SENT.total
stats['stat.net.SENT.rps'] = box_stat_net.SENT.rps
stats['stat.net.RECEIVED.total'] = box_stat_net.RECEIVED.total
stats['stat.net.RECEIVED.rps'] = box_stat_net.RECEIVED.rps
```

2019-03-14 10:58 UTC, merged